fixed creating snapshots of /
added [recursive] option to create configs
allows to take non recursive snapshots of for example /

diff --git a/snapshooter b/snapshooter
--- a/snapshooter
+++ b/snapshooter
@@ -26,8 +26,8 @@ echo "Detailed documentation available at https://github.com/Finic8/snapshooter"
 exit 2
 }
 [ $# -eq 0 ] && printusage
-
-if [ $1 == 'create' ]; then
+mode=$1
+if [ $mode == 'create' ]; then
 	for (( i=${#periods[@]}; i>0; i-- )); do
 		if [[ ${periods[$i-1]} == "$2" ]]; then
 			break
@@ -39,7 +39,7 @@ if [ $1 == 'create' ]; then
 		fi
 	done
 	configs=$configdir/create/*.conf
-elif [ $1 == 'send' ]; then
+elif [ $mode == 'send' ]; then
 	if [ -z "$2" ]; then
 		configs=$configdir/send/*.conf
 	else
@@ -53,7 +53,7 @@ elif [ $1 == 'send' ]; then
 			fi
 		done
 	fi
-elif [ $1 == '--help' ]; then
+elif [ $mode == '--help' ]; then
 	printusage
 else
 	echo "invalid option"
@@ -83,9 +83,20 @@ getnames () {
 		done
 	else
 		IFS=',' read -ra names <<< "$name"
+		[ "$mode" != "create" ] && { recursive=yes; }
 		for possname in ${names[@]}; do
-			content=$(btrfs subvolume list -o $snapdir | awk -F/ '{print $NF}' | grep $possname)
-			[ -z "$content" ] && { echo "ERROR: $possname does not exist"; exit 6; }
+			if [ "$recursive" == "no" ]; then
+				if [ -n "$(btrfs subvolume show $snapdir | grep "ERROR")" ]; then
+					echo "ERROR: $snapdir is not a btrfs subvolume"
+					exit 13
+				fi
+			elif [ "$recursive" == "yes" ]; then
+				content=$(btrfs subvolume list -o $snapdir | awk -F/ '{print $NF}' | grep $possname)
+				[ -z "$content" ] && { echo "ERROR: $possname does not exist"; exit 6; }
+			else
+				echo "ERROR: $config : recursive can only be set to yes or no"
+				exit 14
+			fi
 		done
 	fi
 }
@@ -205,7 +216,12 @@ sendsnaps () {
 createsnaps () {
 	for snapname in ${names[@]}; do
 		echo "creating a $1 snapshot of $snapname"
-		btrfs subvolume snapshot -r $snapdir/$snapname $destination/$prefix$snapname"_$(date +%Y-%m-%d_%H:%M:%S)_$1$postfix"
+		if [ "$recursive" == "no" ]; then
+			sourcesnap=$snapdir
+		else
+			sourcesnap=$snapdir/$snapname
+		fi
+		btrfs subvolume snapshot -r $sourcesnap $destination/$prefix$snapname"_$(date +%Y-%m-%d_%H:%M:%S)_$1$postfix"
 		cleanup
 	done
 }
@@ -236,7 +252,7 @@ do
 	[ ! -d $snapdir ] && { echo "ERROR: snapdir does not exist"; exit 5; }
 	getnames
 	echo "names ${names[@]}"
-	if [ $1 == 'create' ];then
+	if [ $mode == 'create' ];then
 		createsnaps $2
 	else
 		if [ -n "$sshlogin" ]; then 
@@ -245,8 +261,10 @@ do
 		sendsnaps
 	fi
 	unset ntk
+	unset names
 	unset snapdir
 	unset destination
+	unset recursive
 	unset sshlogin
 	unset mac
 	unset ip
